# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pm_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pm_user_type',
                'managed': False,
            },
        ),
    ]
