# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('auth_user_id', models.OneToOneField(db_column='auth_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pmUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_user',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pm_user_type',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserType'),
        ),
    ]
