# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={},
        ),
    ]
