# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 15:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounting_factor', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_benefits_for_no_of_years', models.PositiveIntegerField(blank=True, null=True)),
                ('accelerated_depreciation', models.CharField(blank=True, max_length=64, null=True)),
                ('area_required_for_1KW_plant_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_generated_per_annum_per_kw', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_of_plant_including_batteries_for_1kw', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_of_plant_without_batteries_for_1kw', models.PositiveIntegerField(blank=True, null=True)),
                ('decrease_in_plant_output_1styear', models.PositiveIntegerField(blank=True, null=True)),
                ('decrease_in_plant_output_everyyear_after_1styear', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_basic_assumptions',
            },
        ),
        migrations.CreateModel(
            name='EPC_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('registered_name', models.CharField(blank=True, max_length=64, null=True)),
                ('epc_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('about_epc', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('projects_in_india', models.PositiveIntegerField(blank=True, null=True)),
                ('projects_outside_india', models.PositiveIntegerField(blank=True, null=True)),
                ('executed_projects', models.PositiveIntegerField(blank=True, null=True)),
                ('ongoing_projects', models.PositiveIntegerField(blank=True, null=True)),
                ('references_to_verify', models.CharField(blank=True, max_length=64, null=True)),
                ('cost_quality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('annual_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_for_building_plant', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('feasible_in_house_plant', models.CharField(blank=True, max_length=64, null=True)),
                ('module_manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('inverter_manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('wiring_cost_range', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('civil_work_range', models.CharField(blank=True, max_length=64, null=True)),
                ('labor', models.CharField(blank=True, max_length=64, null=True)),
                ('total_cost_range', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('sme_range', models.CharField(blank=True, max_length=64, null=True)),
                ('cibil', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pm_epc_details',
            },
        ),
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc_Details', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_details', models.CharField(blank=True, max_length=64, null=True)),
                ('units_generated', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('no_of_units_generated', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Revnue', models.PositiveIntegerField(blank=True, null=True)),
                ('operation_and_maintainance', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_replacement_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('miscellaneous', models.CharField(blank=True, max_length=200, null=True)),
                ('commission_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('total_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_project_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_project_status',
            },
        ),
        migrations.CreateModel(
            name='Solar_Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_toparea_info', models.PositiveIntegerField(blank=True, null=True)),
                ('solution_for', models.CharField(choices=[('home', 'Home'), ('society', 'Society'), ('industry', 'industry')], max_length=20)),
                ('consumption_per_month', models.CharField(blank=True, max_length=64, null=True)),
                ('avg_bill_per_month', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')])),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pm_solar_estimator',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobiles',
        ),
        migrations.AddField(
            model_name='user',
            name='IRR_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cibil_report',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consumption',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feasible_in_house_plant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='financail_document_upload',
            field=models.FileField(blank=True, null=True, upload_to=users.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_amount_to_invest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='min_amount_to_invest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='plant_size_per_RT_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plant_size_per_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price_escalation_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rooftop_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_bill_with_taxes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_per_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_unit_consumption',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='willing_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserType'),
        ),
        migrations.AddField(
            model_name='solar_estimator',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_details',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_details',
            name='epc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_epc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_details',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_details',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='epc_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
