# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171121_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epc_details',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='solar_estimator',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='financail_document_upload',
            new_name='financial_document_upload',
        ),
        migrations.AlterField(
            model_name='project_details',
            name='battery_replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='commission_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='created_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='created_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='solar_estimator',
            name='roof_toparea_info',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
