# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171130_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='epc_review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
