# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_project_details_epc_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_profile',
            new_name='consumer_profile',
        ),
        migrations.RemoveField(
            model_name='project_details',
            name='customer',
        ),
        migrations.AddField(
            model_name='project_details',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_consumer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
